### ISSUE TITLE
Langflow support?

### ISSUE THREAD

**Issue by jasgeo75** [kreneskyp/ix#147]
First off, great work!   Love the chain builder, it'd be great to see more support for things like Retrieval QA and Doc Loaders and text splitters.    Have you considered adding support for Langflow?

**Comment by kreneskyp** [comment]
> it'd be great to see more support for things like Retrieval QA and Doc Loaders and text splitters.

Indexing and retrieval components are on the roadmap. No specific timeline but there have been a few requests for this.

> Have you considered adding support for Langflow?

No, direct support isn't very likely. The chain editor and Langflow serve the same purpose. There are also some config and chain incompatibilities that would need to be resolved first.

**Comment by jasgeo75** [comment]
> Indexing and retrieval components are on the roadmap. No specific timeline but there have been a few requests for this.

That's good news, thanks.

> No, direct support isn't very likely. The chain editor and Langflow serve the same purpose. There are also some config and chain incompatibilities that would need to be resolved first.

Understood.  The reason I suggested it was primarily the fact that langflow lets you test your flow as you go which makes development of chains, etc easier.  The ability to import/export would be very nice  though.

On a side note, another nice to have feature be to have more control over the chats, such as being able to label them and delete them from the list.  I'm acquiring a lot of cruft and its currently difficult to know which chat is which.

**Comment by kreneskyp** [comment]
> Understood. The reason I suggested it was primarily the fact that langflow lets you test your flow as you go which makes development of chains, etc easier. The ability to import/export would be very nice though.

Yes to improved debugging and import/export.

- Chat in the editor: Most of the existing functionality for chat can be extended to work. Needs some minor work to pull it together.  #152
- import/export: This probably doesn't happen until after retrieval components are done. I want the full picture of components before trying to refine loading process to support import/export.

> On a side note, another nice to have feature be to have more control over the chats, such as being able to label them and delete them from the list. I'm acquiring a lot of cruft and its currently difficult to know which chat is which.

This is planned but needs a decent amount of work. Opened #151 to track it.

**Comment by YamonBt** [comment]
The IX project is awesome, but two projects with the same purpose don't seem healthy. Since various LLMs will be released and updated, I think it should be redesigned with Langflow to prepare for it.

**Comment by YamonBt** [comment]
Your work is impressive, and I'd like to contribute to your project. We plan to fork the IX project, create a wrapper using Langflow's custom chain, and conduct independent research to contribute to IX.

**Comment by kreneskyp** [comment]
>  it'd be great to see more support for things like Retrieval QA and Doc Loaders and text splitters. 

@jasgeo75 

Initial support for retrieval components has landed:
-  #170   
-  https://github.com/kreneskyp/ix/pull/172

Basic workflows for file-ingestion+QA and QA (with pre-populated db) are functional.  Initial work focuses on generic loaders for the components.  Broader set of components, ingestion tools will come in follow up work.

I'm looking for testers, feedback, and component builders. Please open issues for feature requests for specific loader/retriever components you'd like to use and workflows you'd like to build.

Closing this ticket since Langflow likely won't be supported.
