### ISSUE TITLE
main.js permission errors in Nginx

### ISSUE THREAD

**Issue by jasgeo75** [kreneskyp/ix#148]
Occasionally, I'm seeing these errors in the nginx container.  The app is unusable once these start popping up.

ix-nginx-1  | 2023/08/01 19:46:21 [error] 27#27: *520 open() "/var/static/js/main.js" failed (13: Permission denied), client: 172.18.0.1, server: 0.0.0.0, request: "GET /static/js/main.js HTTP/1.1", host: "localhost:8000", referrer: "http://localhost:8000/"

**Comment by kreneskyp** [comment]
Can you run `make bash` and then check the user/group on `/var/static/js/main.js`?

This may be related to the docker container running as a different user and uid than the host.
