### ISSUE TITLE
Permission denied when run dev_setup

### ISSUE THREAD

**Issue by JRBusiness** [kreneskyp/ix#166]
Running `make dev_setup` giving me "denied" error when it trying to run the web container.
`Error response from daemon: Head "https://ghcr.io/v2/kreneskyp/ix/sandbox/manifests/latest": denied
make: *** [Makefile:94: npm_install] Error 18`

When I query the url "https://ghcr.io/v2/kreneskyp/ix/sandbox/manifests/latest"  I got this
'{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}'

**Comment by kreneskyp** [comment]
The image is probably missing from your environment but Make isn't detecting it.

1. `make clean` to clear build artifacts
2. `make setup` should then build the image.

**Comment by JRBusiness** [comment]
Thank you, I will try that and give feedback.

**Comment by JRBusiness** [comment]
@kreneskyp Hi, running `make setup` give me this "make: *** No rule to make target 'setup'.  Stop."

**Comment by kreneskyp** [comment]
oh whoops.  That's supposed to be `make dev_setup`

**Comment by JRBusiness** [comment]
@kreneskyp Thank you once again for the fast reply and the active development. I am able to run it now, I will give feedback if I ever encounter any problem. :hatoff:

**Comment by JRBusiness** [comment]
Got it fixed by using the tool `dos2unix` and execute the command `dos2unix manage.py`
