### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by JRBusiness** [kreneskyp/ix#167]
I got 
```
ix-web-1    | INFO:     172.18.0.5:48972 - "GET / HTTP/1.0" 200 OK
ix-nginx-1  | 172.18.0.1 - - [16/Aug/2023:05:54:30 +0000] "GET / HTTP/1.1" 200 174 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
ix-web-1    | INFO:     ('172.18.0.5', 48978) - "WebSocket /graphql-ws/" [accepted]
ix-web-1    | INFO:     connection open
ix-web-1    | Bad Request: /graphql
ix-web-1    | INFO:     172.18.0.5:48982 - "POST /graphql HTTP/1.0" 400 Bad Request
ix-nginx-1  | 172.18.0.1 - - [16/Aug/2023:05:54:30 +0000] "POST /graphql HTTP/1.1" 400 118 "http://localhost:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
ix-web-1    | INFO:     172.18.0.5:48984 - "GET /favicon.ico HTTP/1.0" 200 OK
ix-nginx-1  | 172.18.0.1 - - [16/Aug/2023:05:54:30 +0000] "GET /favicon.ico HTTP/1.1" 200 174 "http://localhost:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
```

 When trying to access the app from "http://localhost:8000"
 
 The loading circle just keep spinning..

**Comment by JRBusiness** [comment]
And also when I run `make worker` it also return 
```exec /usr/bin/ix/celery.sh: no such file or directory
make: *** [Makefile:136: worker] Error 1```

similar to #74

**Comment by kreneskyp** [comment]
> When trying to access the app from "http://localhost:8000/"

> The loading circle just keep spinning..


Need to rebuild frontend with `make frontend`.

Your browser may also cache the javascript so you may need to `shift+F5` or `shift+r` to force a refresh depending what operating system you're on.

> And also when I run make worker similar to https://github.com/kreneskyp/ix/issues/74 it also return

I'm not sure what this one is.  Will need to investigate further.

**Comment by JRBusiness** [comment]
Thanks, I will install linux distro and try to run it on pure linux to see if the problem #74 is wsl exclusive.

**Comment by JRBusiness** [comment]
@kreneskyp I can confirm that in linux, everything work out of the box. So there is some compatible issue with wsl.
