### ISSUE TITLE
Potentially broken imports

### ISSUE THREAD

**Issue by BillSchumacher** [kreneskyp/ix#242]
Looks like CommandRegistry was deleted.

![image](https://github.com/kreneskyp/ix/assets/34168009/355f36dd-681d-4914-8adc-bfa45a3e92a5)

and load_llm

![image](https://github.com/kreneskyp/ix/assets/34168009/ca32ea75-d17c-4295-bcb5-7aa80f08eedb)

**Comment by kreneskyp** [comment]
Thanks for the bug report. Did this surface while running?  Looks like all defunct code.

**Comment by BillSchumacher** [comment]
I didn't actually run it yet, I was just browsing the code. I have some other projects I'm working on atm.
