### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by Artsen** [kreneskyp/ix#249]
I have followed the instructions step-by-step but I am still running into errors. I can get the docker cluster to run: bd-1, nginx-1, redis-1, web-1 but worker-1 will not stay up with the following error: `exec /usr/bin/ix/celery.sh: no such file or directory`

additionally when i try to go to the web interface i get just a blank white screen and an error saying /static/js/main.js tossing "ERR_CONNECTION_REFUSED" with nginx throwing: `[error] 29#29: *10 open() "/var/static/js/main.js" failed (2: No such file or directory), client: 172.26.0.1, server: 0.0.0.0, request: "GET /static/js/main.js HTTP/1.1", host: "localhost:8000", referrer: "http://localhost:8000/"` nginx is running on 8000 and web-1 doesnt show any errors and is running on 8001

any tips?

**Comment by kreneskyp** [comment]
What command did you use to start the cluster?

**Comment by Artsen** [comment]
I ran the docker file within the project, i tried using the make dev_setup at first but make would not run for me in windows

**Comment by kreneskyp** [comment]
Are you running in windows or in WSL?

**Comment by Artsen** [comment]
I tried in VSCode and then ran it in WSL but was getting an error about docker wsl2. The docker setting is enabled for wsl2, and wsl2 is installed. When trying to install docker within WSL I was met with errors.

WSL Ubuntu was the build

**Comment by kreneskyp** [comment]
Can you post a stack trace of build errors?

**Comment by Artsen** [comment]
ix@MC-L000:~$ make dev_setup
echo building SANDBOX ghcr.io/kreneskyp/ix/sandbox:47dd2181e8e771de66565b54a6c66e1f
building SANDBOX ghcr.io/kreneskyp/ix/sandbox:47dd2181e8e771de66565b54a6c66e1f
docker build -t ghcr.io/kreneskyp/ix/sandbox:47dd2181e8e771de66565b54a6c66e1f -f Dockerfile  .

The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

For details about using Docker Desktop with WSL 2, visit:

https://docs.docker.com/go/wsl2/

make: *** [Makefile:60: .sentinel/image] Error 1
ix@MC-L000:~$ wsl.exe -l -v
  NAME                   STATE           VERSION
* docker-desktop-data    Running         2
  docker-desktop         Running         2
  Ubuntu                 Running         2

**Comment by Artsen** [comment]
Any pointers?

**Comment by kreneskyp** [comment]
> The command 'docker' could not be found in this WSL 2 distro.

> ix@MC-L000:~$ wsl.exe -l -v
>  NAME                   STATE           VERSION
> * docker-desktop-data    Running         2
>  docker-desktop         Running         2
>  Ubuntu                 Running         2

It looks like docker isn't present in your shell.  I think your shell opened in the `docker-desktop-data` VM instead of the `Ubuntu` VM

Here is what I see when I run `wsl.exe -l -v`

> C:\Users\Peter>wsl.exe -l -v
>  NAME                   STATE           VERSION
> * Ubuntu                 Running         2
>  docker-desktop-data    Running         2
>  docker-desktop         Running         2

Try opening the shell in Ubuntu and the see if docker is available
> wsl.exe -d Ubuntu
> docker --version

**Comment by Artsen** [comment]
make cluster is returning this:
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "celery.sh": executable file not found in $PATH: unknown
make: *** [Makefile:164: cluster] Error 1`

make dev_setup is returning this:
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./manage.py": permission denied: unknown
make: *** [Makefile:148: graphene_to_graphql] Error 1`

**Comment by kreneskyp** [comment]
This file might be missing from the library: `"/vault/config/config.hcl`

**Comment by kreneskyp** [comment]
Does the file `.ix/vault-config.hcl` exist in the directory you were running it from?

```
(venv) peter@DESKTOP-BMB4AFO:~/tmp$ ls .ix
certs  database_init  docker-compose.yml  ix_env.py  nginx.conf  vault-config.hcl  vault.env

```

**Comment by Artsen** [comment]
I tried installing again, and I was able to get the vault to work, however. Now whenever I go to the front-end it just gives me a spinning wheel and it never loads the page. I get a a 500 error for the /api/chats/ as well as Axios ("AxiosError: Request failed with status code 500\n    at settle (webpack-internal:///./node_modules/axios/lib/core/settle.js:24:12)\n    at XMLHttpRequest.onloadend (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:129:66)"), ayncToGenerate.js, etc...

**Comment by kreneskyp** [comment]
The most likely cause is that the database didn't initialize.  You can do that manually with:

```
ix up
ix setup
```

**Comment by Artsen** [comment]
thanks! i tried the ix setup but I got this:

```
Running migrations:
  No migrations to apply.
Loading fixture: fake_user
Installed 1 object(s) from 1 fixture(s)
Loading fixture: agent/ix
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/serializers/base.py", line 314, in save_deferred_fields
    value = deserialize_fk_value(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/serializers/base.py", line 398, in deserialize_fk_value
    obj = default_manager.db_manager(using).get_by_natural_key(*field_value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/app/ix/chains/models.py", line 26, in get_by_natural_key
    return self.get(class_path=class_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
ix.chains.models.NodeType.DoesNotExist: NodeType matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/app/./manage.py", line 22, in <module>
    main()
  File "/var/app/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/app/ix/task_log/management/commands/setup.py", line 23, in handle
    call_command("loaddata", fixture)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 102, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 165, in loaddata
    obj.save_deferred_fields(using=self.using)
  File "/usr/local/lib/python3.11/site-packages/django/core/serializers/base.py", line 318, in save_deferred_fields
    raise DeserializationError.WithData(
django.core.serializers.base.DeserializationError: NodeType matching query does not exist.: (chains.chainnode:pk=##hidden##) field_value was '['langchain.memory.ConversationBufferMemory']'
```

**Comment by kreneskyp** [comment]
Alright I think we're almost to the root of this.  Looks like the `setup` command isn't initializing the components.

```
IX_IMAGE_TAG=latest IX_ENV=../ix.env docker-compose -f .ix/docker-compose.yml run web ./manage.py import_langchain
```

then
 
```
ix setup
```

**Comment by Artsen** [comment]
That did it! you are a legend. Thank you sir.

**Comment by kreneskyp** [comment]
Awesome! Thanks for the patience working through this.

Permanent fix coming in #284

**Comment by kreneskyp** [comment]
Just pushed the fix out in **v0.11.0**

**Comment by kreneskyp** [comment]
Closing this.  Please re-open if you run into anymore issues!

**Comment by happy15** [comment]
> The most likely cause is that the database didn't initialize. You can do that manually with:
> 
> ```
> ix up
> ix setup
> ```

Solved my 500 problem. And I think it would be great it's mentioned in README.md.
