### ISSUE TITLE
make-frontend not working: relay-compiler: not found

### ISSUE THREAD

**Issue by soumym** [kreneskyp/ix#29]
When I'm trying to run `make-frontend` or `make dev_setup`, the process is stopping at the following step
```❯ make frontend
docker-compose run --rm sandbox ./manage.py graphql_schema --out ./frontend/schema.graphql
Creating ix_sandbox_run ... done
Successfully dumped GraphQL schema to ./frontend/schema.graphql
docker-compose run --rm sandbox npm run relay
Creating ix_sandbox_run ... done

> ix@0.1.0 relay
> relay-compiler

sh: 1: relay-compiler: not found
ERROR: 127
make: *** [compile_relay] Error 127
```

I'm using docker-compose on MacOS 12.6 (Intel i-9)
```❯ docker --version
Docker version 20.10.17, build 100c701
```

```❯ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```

Currently on master at commit: "310ff930f1af315562a1df9f3a6efbea79fa3875"

**Comment by kreneskyp** [comment]
@soumym try running `make clean` and then `make frontend` again.  

`relay-compiler` is installed via `package.json`. It's possible your image is out of date but `make` isn't detecting the change.
