### ISSUE TITLE
make dev_setup not working

### ISSUE THREAD

**Issue by BMoankee** [kreneskyp/ix#30]
every time I run make dev_setup I get this 

docker tag ghcr.io/ix/sandbox:351deee50d1620b5f0d4551ce88cba95 ghcr.io/ix/sandbox:latest
touch .sentinel/image
docker-compose run --rm sandbox ./manage.py graphql_schema --out ./frontend/schema.graphql
Dev Containers CLI: RPC pipe not configured. Message: {"args":["docker-credential-helper","get"],"stdin":"https://index.docker.io/v1/"}
Dev Containers CLI: RPC pipe not configured. Message: {"args":["docker-credential-helper","get"],"stdin":"https://index.docker.io/v1/"}
[+] Running 0/0
 ⠋ redis Pulling                                                                                                                                              0.0s
 ⠋ db Pulling                                                                                                                                                 0.0s
error getting credentials - err: exit status 255, out: ``
make: *** [Makefile:73: graphene_to_graphql] Error 1

I tried again from inside VScode and got a little bit different error

Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./manage.py": stat ./manage.py: no such file or directory: unknown
make: *** [Makefile:73: graphene_to_graphql] Error 1

I found this issue in manage.py as well

Import "django.core.management" could not be resolved from source Pylance(reportMissingModuleSource) [Ln 11, Col 14|

**Comment by kreneskyp** [comment]
Does `make image` run?

**Comment by BMoankee** [comment]
Yes it seems so, I get these two lines at the end after running "make image" 

\docker tag ghcr.io/ix/sandbox:351deee50d1620b5f0d4551ce88cba95 ghcr.io/ix/sandbox:latest
touch .sentinel/image

**Comment by kreneskyp** [comment]
I've never seen that error before, Iappears to be related to how your docker is configured. Do you have credential helpers enabled?

Does this drop you into a bash shell?
`docker run -it ghcr.io/ix/sandbox:latest /bin/bash` 

> Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./manage.py": stat ./manage.py: no such file or directory: unknown
make: *** [Makefile:73: graphene_to_graphql] Error 1

This is probably from starting in the wrong working directory.  It should be `/var/app`

**Comment by BMoankee** [comment]
When I run that command it drops me here

root@710c7771f37a:/var/app#

It probably does have something to do with how my docker is configured. Honestly, I'm not very familiar with running docker so I wouldn't be surprised if I configured it incorrectly. What do you suggest I try to resolve this? Do you know if I can change my current configuration or if I start from scratch do you have any suggestions on how I should configure docker?

**Comment by BMoankee** [comment]
When I navigate the file system from the command line it tells me that /var/app does not exist, also looking at the files list in docker desktop app I don't see it there either.

**Comment by kreneskyp** [comment]
> When I run that command it drops me here

> root@710c7771f37a:/var/app#

That looks right.  

> When I navigate the file system from the command line it tells me that /var/app does not exist, also looking at the files list in docker desktop app I don't see it there either.

`/var/app` is the path inside the docker image where the app source code is installed.

**Comment by BMoankee** [comment]
I might have just figured out my issue. It was due to the way I tried to build the image. I could not figure out how to do it from the command terminal. 

However now I've hit another snag, I've rebuilt the container and now when I run make dev_setup it gets hung up on line 35 of the Makefile. I tried running each line one at a time and got this...

# echo building ghcr.io/ix/sandbox:761af16ee0175fb40d112d3b3f609f64
building ghcr.io/ix/sandbox:761af16ee0175fb40d112d3b3f609f64
# docker build -t ghcr.io/ix/sandbox:761af16ee0175fb40d112d3b3f609f64 -f Dockerfile .
/bin/sh: 9: docker: not found

**Comment by kreneskyp** [comment]
> /bin/sh: 9: docker: not found

That means docker isn't available in the context you're running it.  To be clear, you should run `docker build` on your host (sounds like windows + windows linux subsystem in your case?)

> When I explore the file system everything is in /var/app including the Dockerfile I don't understand why it can't see it

Yeah, the whole app is added to `/var/app` for simplicity.  Easier than trying to pick out specific files. 



btw you can find me on discord as @robot3yes.  I'll be out for a bit but I'm usually around.
https://discord.gg/uCKNH4q7
