### ISSUE TITLE
There is a problem displaying the site

### ISSUE THREAD

**Issue by Fovezo** [kreneskyp/ix#59]
Hello, I have a problem displaying the site. Judging by the error it can't find the js file. Can anyone suggest what this is related to?         
ix-nginx-1  | 2023/05/28 17:07:01 [error] 23#23: *4 open() "/var/static/js/main.js" failed (2: No such file or directory), client: 172.18.0.1,

**Comment by kreneskyp** [comment]
Most likely cause is that javascript wasn't built.  Try running `make dev_setup`.

**Comment by Fovezo** [comment]
Today it was updated from the repository and the error that was before does not come out anymore. But the main problem remained - when you go to the site, the interface is not displayed. I apologize in advance. I don't understand how servers work and may not see obvious things. I checked that all containers in Docker started up and I don’t understand how to solve this problem. Additionally, I throw off the code from the terminal and the code that my browser receives when requested. If you need to throw something else, then I'm ready.

$ make server
docker-compose up web nginx
[+] Running 4/0
 ✔ Container ix-db-1     Created                                                                                             0.0s
 ✔ Container ix-redis-1  Created                                                                                             0.0s
 ✔ Container ix-web-1    Created                                                                                             0.0s
 ✔ Container ix-nginx-1  Created                                                                                             0.0s
Attaching to ix-nginx-1, ix-web-1
ix-web-1    | INFO:     Will watch for changes in these directories: ['/var/app']
ix-web-1    | INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
ix-web-1    | INFO:     Started reloader process [1] using WatchFiles
ix-nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
ix-nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
ix-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
ix-nginx-1  | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
ix-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
ix-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
ix-nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
ix-web-1    | INFO:     Started server process [8]
ix-web-1    | INFO:     Waiting for application startup.
ix-web-1    | INFO:     ASGI 'lifespan' protocol appears unsupported.
ix-web-1    | INFO:     Application startup complete.
ix-web-1    | INFO:     172.18.0.5:54080 - "GET / HTTP/1.0" 200 OK
ix-nginx-1  | 172.18.0.1 - - [29/May/2023:10:55:36 +0000] "GET / HTTP/1.1" 200 174 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 YaBrowser/23.3.4.603 Yowser/2.5 Safari/537.36"
ix-web-1    | INFO:     172.18.0.5:49944 - "GET / HTTP/1.0" 200 OK

<html>
<body>


<!DOCTYPE html>
--
  | <html lang="en">
  | <head>
  | <meta charset="utf-8" />
  | <title>Ix</title>
  | <script type="text/javascript" src="/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=ILFZzApufeilPYZdkmE6VbRhqxIugqRWDmUGjpiSLAz7_2yVo2on3vgJBa9Ym1Uo" charset="UTF-8"></script><link rel="stylesheet" crossorigin="anonymous" href="/E3E8934C-235A-4B0E-825A-35A08381A191/abn/main.css?attr=aHR0cDovL2xvY2FsaG9zdDo4MDAwLw"/></head>
  | <body>
  | <div id="root"></div>
  | <script src="/static/js/main.js"></script>
  | </body>
  | </html>


</body>
</html><!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Ix</title>
  <script type="text/javascript" src="[/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=ILFZzApufeilPYZdkmE6VbRhqxIugqRWDmUGjpiSLAz7_2yVo2on3vgJBa9Ym1Uo](http://localhost:8000/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=ILFZzApufeilPYZdkmE6VbRhqxIugqRWDmUGjpiSLAz7_2yVo2on3vgJBa9Ym1Uo)" charset="UTF-8"></script><link rel="stylesheet" crossorigin="anonymous" href="[/E3E8934C-235A-4B0E-825A-35A08381A191/abn/main.css?attr=aHR0cDovL2xvY2FsaG9zdDo4MDAwLw](http://localhost:8000/E3E8934C-235A-4B0E-825A-35A08381A191/abn/main.css?attr=aHR0cDovL2xvY2FsaG9zdDo4MDAwLw)"/></head>
  <body>
    <div id="root"></div>
    <script src="[/static/js/main.js](http://localhost:8000/static/js/main.js)"></script>
  </body>
</html>

**Comment by kreneskyp** [comment]
Does the `.compiled-static` directory exist in the project directory?

If not, run this in your terminal:
```
make dev_setup
```

**Comment by Fovezo** [comment]
Yes, this directory exists. Before that, I checked that further in the js folder there is main.js

**Comment by kreneskyp** [comment]
Please re-open if you're still having issues.
