### ISSUE TITLE
:bug: Unexpected Application Error! agent.chain is null

### ISSUE THREAD

**Issue by yangkyeongmo** [kreneskyp/ix#68]
# Outcome

- I met error same as the title.

# Expected outcome

- I expected to see default agents or be able to remove the agent causing the error.

# To duplicate

1. `make dev_setup`
2. `make server`
3. `make worker`
4. Create an agent without "Chain"
5. Access agent list

# Screenshots

This is when I created an agent,
![Screenshot from 2023-06-03 00-17-52](https://github.com/kreneskyp/ix/assets/24609628/fc412628-d358-4ad3-a6ae-112578d984bc)

And this is when I accessed agent list.
![Screenshot from 2023-06-03 00-14-49](https://github.com/kreneskyp/ix/assets/24609628/9ceaba67-b403-44d9-bef1-4d423c242307)

I couldn't remove the agent from UI, but maybe I could remove the agent somehow in DB.. but I didn't look at it yet.

**Comment by kreneskyp** [comment]
Sorry for the slow reply. A quick work around is to reset the database.

```
make bash
```
```
./manage.py reset_db
```

Then exit the container shell and re-run dev_setup
```
make dev_setup
```
