### ISSUE TITLE
exec /usr/bin/ix/celery.sh: no such file or directory

### ISSUE THREAD

**Issue by dralucindaodonto** [kreneskyp/ix#74]
PS E:\ix2\ix> make worker
docker-compose run --rm web celery.sh
[+] Building 0.0s (0/0)
[+] Creating 2/0
 ✔ Container ix-redis-1  Running                                                              0.0s 
 ✔ Container ix-db-1     Running                                                              0.0s 
[+] Building 0.0s (0/0)
exec /usr/bin/ix/celery.sh: no such file or directory
make: *** [worker] Error 1

**Comment by kreneskyp** [comment]
Try running `make bash`  to open a shell in the container.  Does the file exist in the container?

**Comment by JRBusiness** [comment]
That error isn't indicate that celery.sh is missing, instead it because it cannot find the file that mentioned inside the celery.sh which is 
`DJANGO_SETTINGS_MODULE=ix.server.celery_settings`

**Comment by kreneskyp** [comment]
> I can confirm that in linux, everything work out of the box. So there is some compatible issue with wsl.

`celery.sh` should be added to the docker image. Can you run `make bash` and check whether the file exists?

**Comment by kreneskyp** [comment]
believe this was fixed by #366
